name = "Athena Remastered";
picture = "";
logo = "";
logoOver = "";
tooltip = "Athena Remastered";
tooltipOwned = "Athena Remastered";
overview = "A real-time second-screen tactical map for Arma 3. Live Blue-Force Tracker with terrain, NATO symbology, and event feed.";
author = "SgtFoose";
authorUrl = "https://steamcommunity.com/sharedfiles/filedetails/?id=3687225607";
version = "1.1.4";
versionStr = "1.1.4";
versionAr[] = {1, 1, 4};
